### ISSUE TITLE
Not working (various problems)

### ISSUE THREAD

**Issue by reagle** [KarrLab/gdoc_down#1]
`gdoc_down -f docx  https://docs.google.com/document/d/1JBwkJta-fGiQOrz04slmunjUZHwQXPqwfHFG0dOrOKQ/edit\#`

resulted in:

`No such file or directory: '/Users/reagle/.gdoc_down/auth.json'`

I then created that directory and got:

`IOError: [Errno 2] No such file or directory: 'https://docs.google.com/document/d/1JBwkJta-fGiQOrz04slmunjUZHwQXPqwfHFG0dOrOKQ/edit#'`

Not sure what I'm supposed to be doing.

**Comment by jonrkarr** [comment]
I changed gdoc_down to automatically create the directory for the
credentials, as you correctly did.

gdoc_down is intended to be used with Google Backup & Sync, e.g.
>
> gdoc_down -f docx /Users/reagle/Google\ Drive/my_doc.gdoc


We have clarified this in the documentation.
